name: music
on:
  issues:
    types: [opened,edited]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-workflow-queue@v1
    - run: |
          mkdir -p ./id
          echo $ID > ./id/id
      env:
          ID: ${{ github.event.issue.number }}
    - uses: actions/upload-artifact@v3
      with:
          name: id
          path: id/
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-main${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: |
        git clone -b store https://github.com/xqy2006/musicgen.git "result"
        python3 -m pip install -U git+https://github.com/facebookresearch/audiocraft#egg=audiocraft
        python main.py "$BODY" "$ID"
        ls
      env:
          BODY: ${{ github.event.issue.body }}
          ID: ${{ github.event.issue.number }}
    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: store
        folder: result
    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ github.event.issue.body }}
        split-by: "描述 \n "
    - uses: mad9000/actions-find-and-replace-string@2
      id: findandreplace
      with:
        source: ${{ steps.split.outputs._1}} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
        find: "\n"        # we want to remove ref/heads/ from source 
        replace: ''               # and replace it with a blank string (ie. removing it)
    - run: |
        python sleep.py $ID
        echo OK!
      env:
        ID: ${{ github.event.issue.number }}
    - name: Create comment
      uses: actions-cool/issues-helper@v2
      with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 ${{ github.event.issue.user.login }} ，生成结果如下：
            https://xqy2006.github.io/music_generation/music/${{ github.event.issue.number }}.wav
    - name: Close issue
      uses: actions-cool/issues-helper@v2
      with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
